version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - essay-network
    command: npm run dev -- --host 0.0.0.0

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - essay-network
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  essay-network:
    driver: bridge

volumes:
  node_modules: