services:
  - type: web
    name: essay-scorer-backend
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PORT
        value: 8000

  - type: web
    name: essay-scorer-frontend
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        fromService:
          name: essay-scorer-backend
          type: web
          property: host  # Changed from 'url' to 'host'